/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.github.njustus.swarchitectureanalyzer

import org.slf4j.LoggerFactory

import java.nio.file.Paths

object App {
  val log = LoggerFactory.getLogger(this.getClass)

  def main(args: Array[String]): Unit = {
    val jarPath = Paths.get(args.head)
    log.info(s"reading jar file: $jarPath")

  }
}
